### PR TITLE
Add `Monoid` instance

### PR DESCRIPTION
**Pull request by pseudonom**

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks!

I generalized it to any `Vector` btw.

**Comment by pseudonom** [comment]
Thanks! Out of curiosity, why is the `Applicative` instance not generalized in the same way?

**Comment by expipiplus1** [comment]
The type class `VG.Vector` is predicated on the element type which isn't in scope when declaring an instance for `Applicative`. It might be possible to get around this using some unpalatable extensions, but seeing as `Applicative` uses `a -> b` as an element type in `<*>`, boxed vectors are the only ones that fit anyway.

**Comment by pseudonom** [comment]
Ah, makes sense. Thanks.

**Pull request merged**
