### PR TITLE
Add instance ... VG.Vector v a => Ix (Vector v n a)

### PR DESCRIPTION
**Pull request by mpilgrem**
Further to #50, this may also be of interest: I wondered if `instance (Ix a) => Ix (Vector V.Vector n a)` could be made more general.

This pull request proposes `instance (Ix a) => (Vector v n a)` or, more precisely:

`instance ([Item (v a)] ~ Item (v [a]), Foldable v, IsList (v a), IsList (v [a]), Ix a, MonadZip v, Monoid (v a), Ord (v a)) => Ix (Vector v n a)`

### CODE REVIEW

**Comment by mstksg** [comment]
Hm, I'm not sure that going through `IsList` is necessarily the way, considering that we're only using it to hijack list comprehensions.

We could code the logic from scratch, but there's a simple option as well -- for `range` we could just `fmap VG.Convert` at the end of the current monomorphic version; things might be more performance-wise as the list-based implementation because that's how the `IsList` instance.

This way we wouldn't have to have overlapping instances either.

**Comment by mpilgrem** [comment]
@mstksg, please could you elaborate further on how `Data.Vector.Generic.convert :: (Vector v a, Vector w a) => v a -> w a` could be used.

On performance, in the case of `Ix a => Ix (Vector Vector n a)`, I reasoned (perhaps wrongly) that lists were quite efficient for the `enumerate' (xs:xss) = [ x : xs' | x <- xs, xs' <- enumerate' xss ]` part and that the `map V.fromList $ enumerate' (V.toList v)` 'overhead' was likely tolerable. I was hoping that the compiler would itself do something 'clever' behind the scenes. I probably do not know enough myself about how to reason about Haskell performance to optimise.

**Comment by mstksg** [comment]
What i mean is that we already have a

```
import qualified Data.Vector.Generic.Sized as SVG
import qualified Data.Vector.Generic as VG
import qualified Data.Vector as V

rangeVec
    :: (SVG.Vector V.Vector n a, SVG.Vector V.Vector n a)
    -> [SVG.Vector V.Vector n a]
```

We could write a generic `range` for all `VG.Vector` instances by using:

```
genericRange
    :: VG.Vector v a
    => (SVG.Vector v n a, SVG.Vector v n a)
    -> [SVG.Vector v n a]
genericRange (v, u) = SVG.convert <$> rangeVec (SVG.convert v, SVG.convert u)
```

**Comment by mpilgrem** [comment]
@mstksg, as you say, we do have a `rangeVec` \ `range`:

````haskell
range :: Ix a => (SVG.Vector V.Vector n a, SVG.Vector V.Vector n a) -> [SVG.Vector V.Vector n a]
range (SVG.Vector l, SVG.Vector u) = SVG.Vector <$> enumerate ranges
   where
    ranges = V.zipWith (curry range) l u
    enumerate v
      | V.null v = [V.empty]
      | otherwise = map V.fromList $ enumerate' (V.toList v)
    enumerate' [] = [[]]
    enumerate' (xs:xss) = [ x : xs' | x <- xs, xs' <- enumerate' xss ]
````
Each type of vector type is an instance of the `IsList` class (which class promises the availability of `toList` and `fromList` functionality). That means, at least in principle, that each type of vector's version of those functions could be specific to it. Given that, I do not follow the advantage of converting to/from `V.Vector` in order to make use of the `V.Vector`-specific version of  `toList` and `fromList`.

Is your principal suggestion that it is possible to write a more efficient version of `range` by looking to the functions promised by the underlying `Data.Vector.Generic.Mutable.Base.MVector` class? I was put off by the warning 'Methods of this class should not be used directly.'.

(As an aside, the reason I retained `instance Ix a => Ix (SVG.Vector V.Vector n a)` was not the specialised version of `toList` \ `fromList` but because the `MonadZip` class does not promise a `zipwith3` function. I reasoned that, perhaps, the `V.zipwith3` function was more efficient than a more general replica built up with `MonadZip` functionality - especially when combined with `V.and` in `inRange`.)

**Comment by mpilgrem** [comment]
@mstksg, would something like this be better? It uses the low level functionality promised by `class MVector (Mutable v) a => Vector v a`.

````haskell
instance {-# OVERLAPPABLE #-} (Enum a, Foldable v, Ix a, KnownNat n, MonadZip v,
  Ord (v a), VG.Vector v a) =>
  Ix (Vector v n a) where

  -- range is consistent with range :: ((a,..,a), (a,..,a)) -> [(a,..,a)]
  range (Vector l, Vector u) = if isValid (n - 1)
    then Vector <$> unfoldr generate (Just l)
    else []
   where
    n = fromIntegral (natVal (Proxy :: Proxy n))
    generate = fmap (\v -> (v, next (n - 1) v))
    next i v = if i >= 0
      then unId $ do
        x <- VG.basicUnsafeIndexM v i
        b <- VG.basicUnsafeIndexM l i
        t <- VG.basicUnsafeIndexM u i
        let isTop = x >= t
            x' = if isTop then b else succ x
            v'' = runST $ do
                v' <- VGM.basicUnsafeNew n
                VG.basicUnsafeCopy v' v
                VGM.basicUnsafeWrite v' i x'
                VG.basicUnsafeFreeze v'
        if isTop
          then pure $ next (i - 1) v''
          else pure $ Just v''
      else Nothing
    isValid i = (i >= 0) && unId (do
      b <- VG.basicUnsafeIndexM l i
      t <- VG.basicUnsafeIndexM u i
      pure $ b <= t && (i == 0 || isValid (i - 1)))
````

**Comment by mpilgrem** [comment]
@mstksg, I settled on `instance (Ix a, Ord (v a), VG.Vector v a) => Ix (Vector v n a)`, without overlapping, and made use of the functions exported by `Data.Vector.Generic`.

For a while, I thought I could avoid `toList` \ `fromList` by `Enum a` and `succ`, but then I realised that `Enum a` was too restrictive and, ultimately, I did need `range :: (a, a) -> [a]` - and the value of `range (l, u)` is a list.

**Comment by mstksg** [comment]
Looks great to me :)

**Comment by expipiplus1** [comment]
thanks!

**Pull request merged**
