### PR TITLE
Add zipVectorUnsafe

### LINKED ISSUE #95: zipVectorUnsafe
I [recently needed](https://github.com/Bodigrim/arithmoi/pull/208/files#diff-7e4c4fb9b7f0c60e49916fd572bf7810R51) a generalization of `withVectorUnsafe`, operating on two vectors:

```haskell
zipVectorUnsafe :: (u a -> v b -> w c) -> Vector u n a -> Vector v n b -> Vector w n c 
```

Would a PR adding such function be accepted?

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #95

### CODE REVIEW

**Comment by kozross** [comment]
Should this require a version bump, @expipiplus1 and @mstksg ?

**Comment by expipiplus1** [comment]
Just a minor version bump.

I'm happy with zipVectorUnsafe, however how do you feel about the name withVectorUnsafe2, @bodigrim? As this is not just restricted to zipping? Otoh I like zipVectorUnsafe as it better reflects the lengths of input and output vectors.

**Comment by Bodigrim** [comment]
Naming issues are the hardest :) 

I'm open to any option, whatever floats your boat. Maybe `withTwoVectorsUnsafe`?

**Comment by kozross** [comment]
Why not `withVectorsUnsafe`?

**Comment by Bodigrim** [comment]
> Why not `withVectorsUnsafe`?
In future someone might ask for a routine, handling three vectors instead of two.

**Comment by Bodigrim** [comment]
Any conclusion about naming, @kozross and @expipiplus1? I really have a couple of applications for this and do not want to linger.

**Comment by expipiplus1** [comment]
went with 'zipVectorUnsafe`, it makes the relationship between input and output sizes clear and everyone understands `zipVectorUnsafe3`. Will release as soon as PR clears CI

**Comment by expipiplus1** [comment]
I changed it to `zipVectorsUnsafe`, hope that's OK

**Comment by expipiplus1** [comment]
released https://hackage.haskell.org/package/vector-sized-1.4.2

**Comment by Bodigrim** [comment]
Thanks!

**Pull request merged**
