### PR TITLE
Implement ix, _head, _last lenses

### PR DESCRIPTION
**Pull request by k0ral**
As discussed in https://github.com/expipiplus1/vector-sized/issues/22 .

### CODE REVIEW

**Comment by mstksg** [comment]
Hm, I think that common convention is to just export the lenses with their normal non-rank-n type signatures (as traversals) and without the type synonym, and let users use them however they'd like.  It would probably better match convention if we had

```
ix :: Functor f => Finite n -> (a -> f b) -> Vector n a -> f (Vector n b)
```

**Comment by k0ral** [comment]
Done.

**Comment by k0ral** [comment]
Is there any remaining blocking point before merging this code ?

**Comment by mstksg** [comment]
For what it's worth, this looks good to me.

**Comment by k0ral** [comment]
Added `_head` and `_last`.
Added lenses for `Data.Vector.Storable.Sized`.

**Comment by expipiplus1** [comment]
@k0ral I've merged the addition ordering branch. If you rebase on master you'll get that and also travis will work again (thanks, @mstksg!)

**Comment by expipiplus1** [comment]
Oh, if you add to the changelog and bump the version number then I'll do a release :)

**Comment by k0ral** [comment]
Fixed type signature, rebased, bumped version and updated changelog.

**Comment by expipiplus1** [comment]
https://hackage.haskell.org/package/vector-sized-0.6.1.0

**Pull request merged**
