### PR TITLE
Correct type of scan functions

### LINKED ISSUE #76: Function signatures for accumulating folds do not account for increased vector length.
#### Issue description
The signatures for `scanl`, `scanr`, `scanl'`, and `scanr'` in `Data.Vector.Sized` have the functions erroneously return a vector of equal size to the input. The second argument, however, adds to the length of the output vector.

#### Minimal example
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
module Main where

import           GHC.TypeLits      (KnownNat)
import           Data.Vector.Sized (Vector, fromTuple)
import qualified Data.Vector.Sized as V

typeAnnot :: (a -> b -> a) -> a -> Vector n b -> Vector n     a
          -- (a -> b -> a) -> a -> Vector n b -> Vector (n+1) a
typeAnnot = V.scanl

test :: forall n a. (KnownNat n, Show a) => Vector n a -> IO ()
test v = putStrLn . concat $ [ show v
                             , "\nV.length         : ", show . V.length            $ v
                             , "\nlength . V.toList: ", show .   length . V.toList $ v
                             , "\n"
                             ]

main :: IO ()
main = do
    let v :: Vector 4 Int
        v = fromTuple (2, 3, 4, 5)
        w = V.scanl (+) 1 v
    test v
    putStrLn ""
    test w
```

#### Output
```
Vector [2,3,4,5]
V.length         : 4
length . V.toList: 4


Vector [1,3,6,10,15]
V.length         : 4
length . V.toList: 5
```

### PR DESCRIPTION
**Pull request by expipiplus1**
Perhaps the types need some bikeshedding, would it be better with
`1+1+n` or `2+n`?

Fixes #76

### CODE REVIEW

**Comment by mstksg** [comment]
Hm, I don't think either way is perfect.  Maybe the best route would be to pick the visually cleaner one (`n+2`?) and then trust the user to use a nat normalising plugin or some other form of massage?

**Comment by kozross** [comment]
I think 2+n is clear enough. Requiring such a plugin isn't something I think we should do unless absolutely necessary.

**Comment by mstksg** [comment]
My point was that in terms of functionality, no choice will cover all potential use cases.  So there isn't any real way to optimize for functionality (users are forced to massage one way or the other); visual cleanliness is the only meaningful criteria, I think.

**Comment by expipiplus1** [comment]
Okie, in that case I'll keep it as is, the side of the `+` the `n` is on indicates if it's a left or right fold.

**Pull request merged**
