### PR TITLE
Allow deepseq-1.5 and primitive-0.9 to support GHC 9.8

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by Bodigrim** [comment]
As a Hackage trustee I went ahead and made a revision, lest the package is removed from Stackage (https://github.com/commercialhaskell/stackage/issues/7138): https://hackage.haskell.org/package/vector-sized-1.5.0/revisions/

**Comment by Bodigrim** [comment]
@kozross just a gentle reminder.

**Comment by Vekhir** [comment]
@kozross @expipiplus1
Is something blocking this PR adding support for `deepseq` 1.5 and `primitive` 0.9 to `vector-sized` from being merged?

**Comment by kozross** [comment]
@Vekhir and @Bodigrim - sorry I let this one slip. Our CI had some issues on Windows, but I can't see the logs now. Could you re-push so it re-triggers? I can't seem to re-trigger either....

**Comment by Bodigrim** [comment]
@kozross all green now. Good to go? A release with this and #122 would be much appreciated.

**Comment by kozross** [comment]
@Bodigrim Sure thing, I'll cut one in a few hours.

Edit: I cut a release, but I can't upload it to Hackage. @expipiplus1 - mind doing this?

**Comment by expipiplus1** [comment]
@kozross whats your Hackage  username? I'll add you as a maintainer

**Comment by expipiplus1** [comment]
I added koz_ross

**Comment by kozross** [comment]
@Bodigrim and @Vekhir - I cut a release, but I'm having issues building and uploading the docs. Will do that as soon as I figure out what's going on. Sorry again for the delay.

Edit: docs now up too.

**Pull request merged**
