### PR TITLE
[BUGFIX] Fix shiftL/shiftR bug (#99)

### PR DESCRIPTION
**Pull request by mstksg**
Should fix the bug inadvertently introduced by myself in #99:

```
ghci> Just v = V.fromList @_ @7 $ Big <$> [False,True,False,False,True,False,True]
ghci> x
Vector [0,1,0,0,1,0,1]
ghci> x `shiftR` 1
Vector [1,0,0,1,0,1,0]
ghci> x `shiftL` 1
Vector [0,0,1,0,0,1,0]
```

We basically have to implement the shift functions from scratch to preserve size.

### CODE REVIEW

**Comment by expipiplus1** [comment]
/bump minor

Let's see if this works on someone else's branch.

Thanks!

**Comment by expipiplus1** [comment]
Oh, would you be able to add something to the changelog please?

**Comment by kozross** [comment]
We may also want to deprecate the release on Hackage with this bug.

**Comment by expipiplus1** [comment]
> We may also want to deprecate the release on Hackage with this bug.

done

**Comment by mstksg** [comment]
Ah sorry I couldn't get to this over the weekend.  I appreciate the help :)

**Pull request merged**
