### PR TITLE
instance Bits (v a) => Bits (Vector v n a)

### PR DESCRIPTION
**Pull request by mstksg**
Basically lifts all of the functionality of the [bitvec](https://hackage.haskell.org/package/bitvec) library to work with sized vectors.  Essentially is intended to give `KnownNat n => Bits (Vector U.Vector n Bit)`, but written in a way that doesn't require a dependency on the other library.  Need to take special care of `bit` and `zeroBits` because they generate a vector from scratch, so the vector has to be the right size.  Other than that, all other functionality can be directly lifted with `coerce`.

This also allows for a `FiniteBits` instance when the unsized vector does not.

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks!

**Comment by mstksg** [comment]
Ahhh I just realized this is wrong!  At least, `shiftL` and `shiftR` inadvertenly change the sizes D:

**Comment by mstksg** [comment]
```
ghci> x = V.fromList $ Bit <$> [False,True,False,False,True,False,True]
ghic> x
[0,1,0,0,1,0,1]
ghci> x `shiftR` 1
[1,0,0,1,0,1]
ghci> x `shiftL` 1
[0,0,1,0,0,1,0,1]
```

I'll be submitting a PR to fix heh, sorry about this.

**Comment by expipiplus1** [comment]
oops!

**Pull request merged**
